<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/MCDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np

rawdata = np.random.randint(low=1, high=15, size=np.random.randint(low=1, high=10, size=(1,2))[0])
data = np.array(rawdata, dtype=np.longdouble)
weights = np.random.random(size = (1, data.shape[1]))
weights = (weights/np.sum(weights))[0]

criterion_type = (np.random.randint(low=0, high=2, size = (1, data.shape[1])))[0]
criterion_type = list(map(lambda x: "max" if x == 1 else "min", criterion_type))

print(data)
print(weights)
print(np.sum(weights))
print(criterion_type)

[[13. 13.  7.  5.]
 [ 1.  7. 13.  1.]
 [12. 13. 13.  4.]
 [14.  9. 11.  7.]
 [10.  9.  2.  4.]
 [ 7.  7.  8.  4.]
 [ 1.  2.  5.  3.]]
[0.22011072 0.27719721 0.2226394  0.28005267]
1.0
['min', 'max', 'max', 'min']


In [39]:
data[:,[0, 2]]

array([[13.,  7.],
       [ 1., 13.],
       [12., 13.],
       [14., 11.],
       [10.,  2.],
       [ 7.,  8.],
       [ 1.,  5.]], dtype=float128)

In [18]:
criterion_type
a = np.array([1, 3, 4, 3, 3, 4, 5])

In [19]:
np.where(np.array(criterion_type) == 'min')[0]
m = data[:, np.where(np.array(criterion_type) == 'min')[0]]
print(m.min(axis=0)/m)

[[0.375      1.        ]
 [1.         0.08333333]
 [0.42857143 0.2       ]
 [0.21428571 1.        ]
 [0.27272727 0.1       ]]


#SAW

In [43]:
def normalize_data(data, criterion_type):
  D = data.copy()
  # max
  dmax = D[:, [np.where(np.array(criterion_type) == 'max')[0]]].copy()
  D[:, [np.where(np.array(criterion_type) == 'max')[0]]] = dmax/dmax.max(axis=0)
  # min
  dmin = D[:, [np.where(np.array(criterion_type) == 'min')[0]]].copy()
  D[:, [np.where(np.array(criterion_type) == 'min')[0]]] = dmin.min(axis=0)/dmin

  return D

n_data = normalize_data(data, criterion_type)
print(n_data)
print(data)


[[0.07692308 1.         0.53846154 0.2       ]
 [1.         0.53846154 1.         1.        ]
 [0.08333333 1.         1.         0.25      ]
 [0.07142857 0.69230769 0.84615385 0.14285714]
 [0.1        0.69230769 0.15384615 0.25      ]
 [0.14285714 0.53846154 0.61538462 0.25      ]
 [1.         0.15384615 0.38461538 0.33333333]]
[[13. 13.  7.  5.]
 [ 1.  7. 13.  1.]
 [12. 13. 13.  4.]
 [14.  9. 11.  7.]
 [10.  9.  2.  4.]
 [ 7.  7.  8.  4.]
 [ 1.  2.  5.  3.]]


In [41]:
criterion_type

['min', 'max', 'max', 'min']

In [ ]:
import numpy as np

def get_user_input():
    num_criteria = int(input("Enter the number of criteria: "))
    criteria = []
    weights = []

    for i in range(num_criteria):
        criterion = input(f"Enter criterion {i + 1}: ")
        weight = float(input(f"Enter weight for {criterion}: "))
        criteria.append(criterion)
        weights.append(weight)

    num_alternatives = int(input("Enter the number of alternatives: "))
    alternatives = []

    for i in range(num_alternatives):
        alternative = []
        print(f"\nEnter data for Alternative {i + 1}:")
        for j in range(num_criteria):
            value = float(input(f"Enter {criteria[j]} for Alternative {i + 1}: "))
            alternative.append(value)
        alternatives.append(alternative)

    return criteria, weights, alternatives

def normalize_data(data):
    return (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))

def calculate_saw_scores(normalized_data, weights):
    weighted_scores = normalized_data * weights
    total_scores = weighted_scores.sum(axis=1)
    return total_scores

def rank_alternatives(total_scores):
    ranked_indices = np.argsort(total_scores)[::-1]
    return ranked_indices

def main():
    criteria, weights, alternatives = get_user_input()

    # Convert data to NumPy array for easier manipulation
    alternatives_data = np.array(alternatives)

    # Step 2: Normalize the data
    normalized_data = normalize_data(alternatives_data)

    # Step 3: Calculate total scores
    total_scores = calculate_saw_scores(normalized_data, weights)

    # Step 4: Rank the alternatives
    ranked_indices = rank_alternatives(total_scores)

    # Display the results
    print("\nResults:")
    for i, index in enumerate(ranked_indices):
        print(f"Rank {i + 1}: Alternative {index + 1} - Total Score: {total_scores[index]:.4f}")

if __name__ == "__main__":
    main()


KeyboardInterrupt: ignored

In [ ]:
x = np.random.randint(0, 8, size = 8)
print(x)
print(np.argsort(x))

[7 3 1 0 7 3 7 4]
[3 2 1 5 7 0 4 6]
