<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/MCDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np

#SAW

In [ ]:

def data_gen():
  rawdata = np.random.randint(low=1, high=15, size=np.random.randint(low=1, high=10, size=(1,2))[0])
  d = np.array(rawdata, dtype=np.longdouble)
  weights = np.random.random(size = (1, d.shape[1]))
  w = (weights/np.sum(weights))[0]

  criterion_type = (np.random.randint(low=0, high=2, size = (1, d.shape[1])))[0]
  c = list(map(lambda x: "max" if x == 1 else "min", criterion_type))
  return d, w, c



# normalization
def normalize_data(data, criterion_type):
  D = data.copy()
  # max
  dmax = D[:, [np.where(np.array(criterion_type) == 'max')[0]]].copy()
  D[:, [np.where(np.array(criterion_type) == 'max')[0]]] = dmax/dmax.max(axis=0)
  # min
  dmin = D[:, [np.where(np.array(criterion_type) == 'min')[0]]].copy()
  D[:, [np.where(np.array(criterion_type) == 'min')[0]]] = dmin.min(axis=0)/dmin

  return D

# calculatopn of saw score
def calculate_saw_scores(normalized_data, weights):
  scores = normalized_data @ weights
  return scores

# ranking
def rank_alternatives(total_scores):
  ranked_indices = np.argsort(total_scores)[::-1]
  # ranked_indices = np.argsort(total_scores)
  return ranked_indices


def main():
  # Step 1:
  data, weights, criterion_type = data_gen()
  # Step 2: Normalize the data
  print(data)
  print(weights)
  print(criterion_type)
  normalized_data = normalize_data(data, criterion_type)
  # Step 3: Calculate total scores
  total_scores = calculate_saw_scores(normalized_data, weights)
  # Step 4: Rank the alternatives
  ranked_indices = rank_alternatives(total_scores)
  # Display the results
  print("\nResults:")
  for i, index in enumerate(ranked_indices):
      print(f"Rank {i + 1}: Alternative {index + 1} - Total Score: {total_scores[index]:.4f}")

if __name__ == "__main__":
    main()



[[ 5. 12. 11. 12.  7.  5.  7. 10.]
 [11.  9. 12.  5.  8.  5.  6.  8.]
 [ 2. 10.  3.  2.  1.  6. 13. 10.]
 [ 5.  8.  1. 10.  1. 13. 14. 12.]
 [ 5.  6.  3.  9.  5.  2.  3.  2.]
 [14.  2.  1.  1. 11.  4.  1.  8.]
 [ 8.  6. 11. 12.  7. 10.  8.  3.]]
[0.12617818 0.05968727 0.05298214 0.14662708 0.17828387 0.15452881
 0.14907566 0.132637  ]
['max', 'max', 'max', 'min', 'max', 'min', 'min', 'max']

Results:
Rank 1: Alternative 6 - Total Score: 0.7802
Rank 2: Alternative 2 - Total Score: 0.5310
Rank 3: Alternative 1 - Total Score: 0.4726
Rank 4: Alternative 5 - Total Score: 0.4118
Rank 5: Alternative 7 - Total Score: 0.3589
Rank 6: Alternative 3 - Total Score: 0.3440
Rank 7: Alternative 4 - Total Score: 0.2872


#SMART

In [61]:
# calculate scores

g = np.array([9, 5, 7, 6])
sq = lambda x: np.power(np.power(2, 0.5) , x)
g = list(map(sq, g))
g = g/np.sum(g)
print(g)

[0.47538608 0.11884652 0.23769304 0.16807436]


In [7]:
np.sqrt(2)**6

8.000000000000004

In [50]:
lower = np.array([20300, 140, 8.2, 230])

# Max Criteria Threshold
upper = np.array([40000, 220, 20, 2000])

# Criterion Type: 'max' or 'min'
criterion_type = ['min', 'max', 'min', 'max']

# Dataset
dataset = np.array([
                    [25000, 153, 15.3, 250],   #a1
                    [33000, 177, 12.3, 380],   #a2
                    [40000, 199, 11.1, 480]    #a3
                   ])

In [51]:
#normalization

dist = upper - lower
print(dist)
dataset = np.log2(64*((dataset - np.tile(lower, (dataset.shape[0],1)))/dist))

D = dataset.copy()
# max
dmax = D[:, [np.where(np.array(criterion_type) == 'max')[0]]].copy()
D[:, [np.where(np.array(criterion_type) == 'max')[0]]] = dmax+4
# min
dmin = D[:, [np.where(np.array(criterion_type) == 'min')[0]]].copy()
D[:, [np.where(np.array(criterion_type) == 'min')[0]]] = -1*dmin+10



[1.97e+04 8.00e+01 1.18e+01 1.77e+03]


In [63]:
print(D)

[[6.06746297 7.37851162 4.73289593 3.53239445]
 [4.63336713 8.88752527 5.52509104 6.43928505]
 [4.         9.56071495 6.02466205 7.17625064]]


In [57]:
# @title Default title text
# SMART

# Grades - From 4 (worst) to 10 (best)
grades = np.array([9, 5, 7, 6])

# Min Criteria Threshold
lower = np.array([20300, 140, 8.2, 230])

# Max Criteria Threshold
upper = np.array([40000, 220, 20, 2000])

# Criterion Type: 'max' or 'min'
criterion_type = ['min', 'max', 'min', 'max']

# Dataset
dataset = np.array([
                    [25000, 153, 15.3, 250],   #a1
                    [33000, 177, 12.3, 380],   #a2
                    [40000, 199, 11.1, 480]    #a3
                   ])

In [58]:
def smart_method(dataset, grades, lower, upper, criterion_type):
    w = np.copy(grades)/1.0
    for i in range(0, w.shape[0]):
        w[i] = (2**(1/2))**w[i]
    w = w/np.sum(w)
    X = np.copy(dataset)/1.0
    for i in range(0, X.shape[1]):
        if ( criterion_type[i] == 'max'):
            X[:,i] =  4 + np.log2( ((dataset[:,i] - lower[i] ) / (upper[i] - lower[i]))*(64) )
        else:
            X[:,i] = 10 - np.log2( ((dataset[:,i] - lower[i] ) / (upper[i] - lower[i]))*(64) )
    print(w)
    Y    = np.sum(X*w, axis = 1)
    print("*******************")
    print(Y)
    flow = np.copy(Y)
    flow = np.reshape(flow, (Y.shape[0], 1))
    flow = np.insert(flow, 0, list(range(1, Y.shape[0]+1)), axis = 1)
    # if (verbose == True):
    #     for i in range(0, flow.shape[0]):
    #         print('a' + str(int(flow[i,0])) + ': ' + str(round(flow[i,1], 3)))
    # if (graph == True):
    #     flow = flow[np.argsort(flow[:, 1])]
    #     flow = flow[::-1]
    #     ranking(flow)
    return flow

In [59]:
rank = smart_method(dataset, grades, lower, upper, criterion_type)

[0.47538608 0.11884652 0.23769304 0.16807436]
*******************
[5.47997922 5.65444409 5.67596599]


In [60]:
rank

array([[1.        , 5.47997922],
       [2.        , 5.65444409],
       [3.        , 5.67596599]])

In [64]:
D@g

array([5.47997922, 5.65444409, 5.67596599])

# BWM