<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/MCDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

data = np.random.randint(low=1, high=15, size=np.random.randint(low=1, high=10, size=(1,2))[0])

weights = np.random.random(size = (1, data.shape[1]))
weights = (weights/np.sum(weights))[0]

criterion_type = (np.random.randint(low=0, high=2, size = (1, data.shape[1])))[0]
criterion_type = list(map(lambda x: "max" if x == 1 else "min", criterion_type))

print(data)
print(weights)
print(np.sum(weights))
print(criterion_type)

[[ 2 14 12  5  8]
 [12 11  6  3 14]
 [10  4  4  3  4]
 [12 14  6 12 12]
 [ 3  5  8  2  4]
 [ 3  1  4  4  8]
 [ 5  9  1 14 13]]
[0.24114717 0.15051052 0.13468742 0.18798263 0.28567225]
0.9999999999999998
['min', 'max', 'min', 'max', 'max']


In [31]:
data[:,[0, 2]]

array([[ 2, 12],
       [12,  6],
       [10,  4],
       [12,  6],
       [ 3,  8],
       [ 3,  4],
       [ 5,  1]])

In [22]:
criterion_type
a = np.array([1, 3, 4, 3, 3, 4, 5])

In [34]:
np.where(np.array(criterion_type) == 'min')[0]
m = data[:, np.where(np.array(criterion_type) == 'min')[0]]
print(m.min(axis=0)/m)

[[1.         0.08333333]
 [0.16666667 0.16666667]
 [0.2        0.25      ]
 [0.16666667 0.16666667]
 [0.66666667 0.125     ]
 [0.66666667 0.25      ]
 [0.4        1.        ]]


#SAW

In [36]:
def normalize_data(data, criterion_type):
  data_max = data[:, [np.where(np.array(criterion_type) == 'max')[0]]]
  data_min = data[:, [np.where(np.array(criterion_type) == 'min')[0]]]
  data_max = data_max/data_max.max(axis=0)
  data_min = data_min.min(axis=0)/data_min
  return data / data.max(axis=0)
  # print(data_max)
  # print(data_min)
  return 0

n_data = normalize_data(data, criterion_type)
print(n_data)

[[[1.         0.35714286 0.57142857]]

 [[0.78571429 0.21428571 1.        ]]

 [[0.28571429 0.21428571 0.28571429]]

 [[1.         0.85714286 0.85714286]]

 [[0.35714286 0.14285714 0.28571429]]

 [[0.07142857 0.28571429 0.57142857]]

 [[0.64285714 1.         0.92857143]]]
[[[1.         0.08333333]]

 [[0.16666667 0.16666667]]

 [[0.2        0.25      ]]

 [[0.16666667 0.16666667]]

 [[0.66666667 0.125     ]]

 [[0.66666667 0.25      ]]

 [[0.4        1.        ]]]
0


In [ ]:
import numpy as np

def get_user_input():
    num_criteria = int(input("Enter the number of criteria: "))
    criteria = []
    weights = []

    for i in range(num_criteria):
        criterion = input(f"Enter criterion {i + 1}: ")
        weight = float(input(f"Enter weight for {criterion}: "))
        criteria.append(criterion)
        weights.append(weight)

    num_alternatives = int(input("Enter the number of alternatives: "))
    alternatives = []

    for i in range(num_alternatives):
        alternative = []
        print(f"\nEnter data for Alternative {i + 1}:")
        for j in range(num_criteria):
            value = float(input(f"Enter {criteria[j]} for Alternative {i + 1}: "))
            alternative.append(value)
        alternatives.append(alternative)

    return criteria, weights, alternatives

def normalize_data(data):
    return (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))

def calculate_saw_scores(normalized_data, weights):
    weighted_scores = normalized_data * weights
    total_scores = weighted_scores.sum(axis=1)
    return total_scores

def rank_alternatives(total_scores):
    ranked_indices = np.argsort(total_scores)[::-1]
    return ranked_indices

def main():
    criteria, weights, alternatives = get_user_input()

    # Convert data to NumPy array for easier manipulation
    alternatives_data = np.array(alternatives)

    # Step 2: Normalize the data
    normalized_data = normalize_data(alternatives_data)

    # Step 3: Calculate total scores
    total_scores = calculate_saw_scores(normalized_data, weights)

    # Step 4: Rank the alternatives
    ranked_indices = rank_alternatives(total_scores)

    # Display the results
    print("\nResults:")
    for i, index in enumerate(ranked_indices):
        print(f"Rank {i + 1}: Alternative {index + 1} - Total Score: {total_scores[index]:.4f}")

if __name__ == "__main__":
    main()


KeyboardInterrupt: ignored

In [ ]:
x = np.random.randint(0, 8, size = 8)
print(x)
print(np.argsort(x))

[7 3 1 0 7 3 7 4]
[3 2 1 5 7 0 4 6]
