<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/MCDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np

data = np.random.randint(low=1, high=15, size=np.random.randint(low=1, high=10, size=(1,2))[0])
weights = np.random.random(size = (1, data.shape[1]))
weights = (weights/np.sum(weights))[0]
criterion_type = (np.random.randint(low=0, high=2, size = (1, data.shape[1])))[0]
criterion_type = list(map(lambda x: "max" if x == 1 else "min", criterion_type))
print(data)
print(weights)
print(np.sum(weights))
print(criterion_type)

[[ 4  5  2  7]
 [ 7  1  5  4]
 [ 4  4  9 10]
 [ 2  3  5 10]
 [10  1 13 14]]
[0.10015473 0.30357527 0.23634032 0.35992968]
1.0
['max', 'min', 'max', 'max']


#SAW

In [40]:
def normalize_data(data, criterion_type):
  data-max
  data-min
  data
  return data / data.max(axis=0)


n_data = normalize_data(data)
print(n_data)

[[0.64285714 0.30769231 0.07692308 0.8        0.66666667]
 [1.         0.07692308 0.46153846 0.7        1.        ]
 [0.57142857 0.46153846 1.         0.8        0.83333333]
 [0.78571429 1.         0.15384615 0.6        0.5       ]
 [0.42857143 0.84615385 0.38461538 1.         0.33333333]]


In [ ]:
import numpy as np

def get_user_input():
    num_criteria = int(input("Enter the number of criteria: "))
    criteria = []
    weights = []

    for i in range(num_criteria):
        criterion = input(f"Enter criterion {i + 1}: ")
        weight = float(input(f"Enter weight for {criterion}: "))
        criteria.append(criterion)
        weights.append(weight)

    num_alternatives = int(input("Enter the number of alternatives: "))
    alternatives = []

    for i in range(num_alternatives):
        alternative = []
        print(f"\nEnter data for Alternative {i + 1}:")
        for j in range(num_criteria):
            value = float(input(f"Enter {criteria[j]} for Alternative {i + 1}: "))
            alternative.append(value)
        alternatives.append(alternative)

    return criteria, weights, alternatives

def normalize_data(data):
    return (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))

def calculate_saw_scores(normalized_data, weights):
    weighted_scores = normalized_data * weights
    total_scores = weighted_scores.sum(axis=1)
    return total_scores

def rank_alternatives(total_scores):
    ranked_indices = np.argsort(total_scores)[::-1]
    return ranked_indices

def main():
    criteria, weights, alternatives = get_user_input()

    # Convert data to NumPy array for easier manipulation
    alternatives_data = np.array(alternatives)

    # Step 2: Normalize the data
    normalized_data = normalize_data(alternatives_data)

    # Step 3: Calculate total scores
    total_scores = calculate_saw_scores(normalized_data, weights)

    # Step 4: Rank the alternatives
    ranked_indices = rank_alternatives(total_scores)

    # Display the results
    print("\nResults:")
    for i, index in enumerate(ranked_indices):
        print(f"Rank {i + 1}: Alternative {index + 1} - Total Score: {total_scores[index]:.4f}")

if __name__ == "__main__":
    main()


KeyboardInterrupt: ignored

In [ ]:
x = np.random.randint(0, 8, size = 8)
print(x)
print(np.argsort(x))

[7 3 1 0 7 3 7 4]
[3 2 1 5 7 0 4 6]
