<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/Metaheuristic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from scipy import optimize

In [ ]:
f = lambda x: x[0]**2 + x[1]**2

In [ ]:
minimum = optimize.fmin(f, x0 = np.array([1,2]), full_output=1,retall = 1 )

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 43
         Function evaluations: 82


5

In [ ]:
minimum

(array([-3.62769110e-05, -3.03662006e-05]),
 2.23812040658642e-09,
 43,
 82,
 0,
 [array([1., 2.]),
  array([1.075, 1.8  ]),
  array([1.0125, 1.7   ]),
  array([1.13125, 1.25   ]),
  array([1.065625, 0.825   ]),
  array([1.184375, 0.375   ]),
  array([ 1.11875, -0.05   ]),
  array([ 1.11875, -0.05   ]),
  array([ 1.11875, -0.05   ]),
  array([ 1.11875, -0.05   ]),
  array([0.97919922, 0.03671875]),
  array([0.97919922, 0.03671875]),
  array([ 0.73613281, -0.2421875 ]),
  array([0.56655273, 0.22148437]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.05126953,  0.06796875]),
  array([-0.05126953,  0.06796875]),
  array([ 0.00706787, -0.03994141]),
  array([ 0.03309021, -0.00236816]),
  array([-0.01559525,  0.02340698]),
  array([ 0.00790768, -0.014711  ]),
  array([0.01462321, 0.00098991]),
  array([-0.0021649 ,  0.00827322]),
  array([-0.

In [ ]:

PE = lambda x: np.sum([
    0.5*(500+200*(5/3-(1))**2)*(np.sqrt((x[0]- 0)**2+(x[5]-0)**2)-10)**2, # first
    np.sum([0.5*(500+200*(5/3-(i+2))**2)*(np.sqrt((x[i+1]-x[i])**2+(x[i+6]-x[i+5])**2)-10)**2 for i in range(4)]),
    0.5*(500+200*(5/3-(6))**2)*(np.sqrt((60-x[4])**2+(0-x[9])**2)-10)**2,# last
    np.sum([50*(i-4)*x[i] for i in range(5, 10)])])

In [ ]:
PE(np.zeros([10]))

5633333.333333332

In [ ]:
minimum = optimize.fmin(PE, x0 = np.array([10, 20, 30, 40, 50, 0, 0, 0, 0, 0]),xtol=1e-7 ,ftol=1e-7,  maxiter=1e10, maxfun = 1e11)

Optimization terminated successfully.
         Current function value: -4416.384186
         Iterations: 5163
         Function evaluations: 7275


In [ ]:
minimum

array([10.35502517, 21.08666164, 31.68693534, 42.08980433, 51.77133989,
       -4.28005284, -7.89735979, -9.85360248, -9.39339913, -6.01179177])

In [ ]:
minimum = optimize.fmin_powell(PE, x0 = np.array([10, 20, 30, 40, 50, 0, 0, 0, 0, 0]),xtol=1e-7 ,ftol=1e-7,  maxiter=1e10, maxfun = 1e11)

Optimization terminated successfully.
         Current function value: -4416.384082
         Iterations: 19
         Function evaluations: 2370


In [ ]:
minimum

array([10.35498682, 21.08667339, 31.68703911, 42.08962064, 51.77133696,
       -4.27972854, -7.89696355, -9.85335753, -9.39325675, -6.01184043])

In [1]:
# import sympy
from sympy import *

x, y = symbols('x y')
expr = (1/2)*8*((x**2+(10-y)**2)**0.5-10)**2 + (1/2)*((x**2+(10+y)**2)**0.5-10)**2 -5*x -5*y
print("Expression : {}".format(expr))

# Use sympy.Derivative() method
expr_diff = Derivative(expr, x)

print("Derivative of expression with respect to x : {}".format(expr_diff))
print("Value of the derivative : {}".format(expr_diff.doit()))
f = lambdify([x, y], expr_diff.doit())
print(f(8.632,4.5319))
expr_diff.doit()

Expression : -5*x - 5*y + 4.0*((x**2 + (10 - y)**2)**0.5 - 10)**2 + 0.5*((x**2 + (y + 10)**2)**0.5 - 10)**2
Derivative of expression with respect to x : Derivative(-5*x - 5*y + 4.0*((x**2 + (10 - y)**2)**0.5 - 10)**2 + 0.5*((x**2 + (y + 10)**2)**0.5 - 10)**2, x)
Value of the derivative : 8.0*x*((x**2 + (10 - y)**2)**0.5 - 10)/(x**2 + (10 - y)**2)**0.5 + 1.0*x*((x**2 + (y + 10)**2)**0.5 - 10)/(x**2 + (y + 10)**2)**0.5 - 5
-0.00039603777435281984


8.0*x*((x**2 + (10 - y)**2)**0.5 - 10)/(x**2 + (10 - y)**2)**0.5 + 1.0*x*((x**2 + (y + 10)**2)**0.5 - 10)/(x**2 + (y + 10)**2)**0.5 - 5

In [2]:
# import sympy
from sympy import *

x, y = symbols('x y')
expr = (1/2)*8*((x**2+(10-y)**2)**0.5-10)**2 + (1/2)*((x**2+(10+y)**2)**0.5-10)**2 -5*x -5*y
print("Expression : {}".format(expr))

# Use sympy.Derivative() method
expr_diff = Derivative(expr, y)

print("Derivative of expression with respect to x : {}".format(expr_diff))
print("Value of the derivative : {}".format(expr_diff.doit()))
g = lambdify([x, y], expr_diff.doit())
print(g(8.632,4.5319))
expr_diff.doit()

Expression : -5*x - 5*y + 4.0*((x**2 + (10 - y)**2)**0.5 - 10)**2 + 0.5*((x**2 + (y + 10)**2)**0.5 - 10)**2
Derivative of expression with respect to x : Derivative(-5*x - 5*y + 4.0*((x**2 + (10 - y)**2)**0.5 - 10)**2 + 0.5*((x**2 + (y + 10)**2)**0.5 - 10)**2, y)
Value of the derivative : 8.0*(1.0*y - 10.0)*((x**2 + (10 - y)**2)**0.5 - 10)/(x**2 + (10 - y)**2)**0.5 + 1.0*(1.0*y + 10.0)*((x**2 + (y + 10)**2)**0.5 - 10)/(x**2 + (y + 10)**2)**0.5 - 5
0.00019505477054426734


8.0*(1.0*y - 10.0)*((x**2 + (10 - y)**2)**0.5 - 10)/(x**2 + (10 - y)**2)**0.5 + 1.0*(1.0*y + 10.0)*((x**2 + (y + 10)**2)**0.5 - 10)/(x**2 + (y + 10)**2)**0.5 - 5

In [3]:
def F(X):
  x = X[0]
  y = X[1]
  return f(x,y)**2 + g(x,y)**2

from scipy import optimize

minimum = optimize.fmin(F, [8, 4])
minimum

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 52
         Function evaluations: 101


array([8.63204955, 4.53189251])

In [6]:
import numpy as np
minimum = optimize.fmin(F, x0 = np.array([10, 9]),xtol=1e-7 ,ftol=1e-7,  maxiter=1e10, maxfun = 1e11)
minimum

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 65
         Function evaluations: 126


array([8.63206613, 4.5319067 ])