<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/Metaheuristic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from scipy import optimize

In [23]:
f = lambda x: x[0]**2 + x[1]**2

In [24]:
minimum = optimize.fmin(f, x0 = np.array([1,2]), full_output=1,retall = 1 )

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 43
         Function evaluations: 82


5

In [25]:
minimum

(array([-3.62769110e-05, -3.03662006e-05]),
 2.23812040658642e-09,
 43,
 82,
 0,
 [array([1., 2.]),
  array([1.075, 1.8  ]),
  array([1.0125, 1.7   ]),
  array([1.13125, 1.25   ]),
  array([1.065625, 0.825   ]),
  array([1.184375, 0.375   ]),
  array([ 1.11875, -0.05   ]),
  array([ 1.11875, -0.05   ]),
  array([ 1.11875, -0.05   ]),
  array([ 1.11875, -0.05   ]),
  array([0.97919922, 0.03671875]),
  array([0.97919922, 0.03671875]),
  array([ 0.73613281, -0.2421875 ]),
  array([0.56655273, 0.22148437]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.00437012, -0.10449219]),
  array([-0.05126953,  0.06796875]),
  array([-0.05126953,  0.06796875]),
  array([ 0.00706787, -0.03994141]),
  array([ 0.03309021, -0.00236816]),
  array([-0.01559525,  0.02340698]),
  array([ 0.00790768, -0.014711  ]),
  array([0.01462321, 0.00098991]),
  array([-0.0021649 ,  0.00827322]),
  array([-0.