<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/ReportOfMNSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In the Name Of God

In [160]:
# importing the requirements
import numpy as np
import time
import scipy as sp
import matplotlib.pyplot as plt

# The raw Form

## Mathematical Benchmarks

### Functions

In [27]:
# RastRigin
# min in (-5, -5)
ObjF_S1 = lambda x: np.power(x[:,0]+5,2) + np.power(x[:,1]+5,2) -10*np.cos(2*np.pi*x[:,0]) -10*np.cos(2*np.pi*x[:,1]) + 20
# Bukin Function
# min in (-10, 1)
ObjF_S2 = lambda x: 100*np.power(np.abs(x[:,1]-0.01*np.power(x[:,0], 2)),0.5)+0.01*np.abs(x[:,0]+10)
# Rosenbrock
# min in (1, 1)
ObjF_S3 = lambda x: 100*np.power(x[:,1]-np.power(x[:,0], 2), 2) + np.power((1-x[:,0]), 2)
# Beale
# min in (3, 0,5)
ObjF_S4 = lambda x: np.power(1.5-x[:,0]+x[:,0]*x[:,1], 2) + np.power(2.25-x[:,0]+x[:,0]*np.power(x[:,1], 2), 2) + np.power(2.625-x[:,0]+x[:,0]*np.power(x[:,1], 3), 2)


### the implementation

In [155]:
# MNSV_S1_1.m

import numpy as np
import matplotlib.pyplot as plt


t1 = time.time()
# Define MNSV Parameters
N = 2                     # Number of variables
NS = 10                    # Number of samples
MAXIT = 40                # Maximum Number of iterations
OBJ_F = ObjF_S1           # Name of objective function
R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
Best = []
xb = []

# Initialization
NP = NS * (NS + 3) // 2
# R1 = np.tile(R[0, :], (NP, 1))
# R2 = np.tile(R[1, :], (NP, 1))
x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
f = OBJ_F(x)                   #evaluation
for it in range(MAXIT):
  ind = np.argsort(f)
  x = x[ind[:NS]]                                         # choosing the best points
  a = np.power(0.3, (it/MAXIT))
  z = a*np.cov(x.T)
  for i in range(NS):
    x = np.append(x, np.random.multivariate_normal(x[i], z, (NS-i)), axis=0)  # appending new points
  x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
  f = OBJ_F(x)                     #evaluation
  xb.append(x[np.argmin(f)])  #save the best
  Best.append(np.min(f))
  #plot
t2 = time.time()
print(t2-t1)

0.05134391784667969


In [156]:
xb

[array([-4.87065907, -3.00692228]),
 array([-4.87065907, -3.00692228]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.0338046 , -5.01744499]),
 array([-4.98891312, -6.0109768 ]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-5.06147135, -4.96390143]),
 array([-4.97742992, -4.97470569]),
 array([-4.97742992, -4.9747

# Modifications

## Covariance based on function

### simple linespace

In [157]:
# MNSV_S1_1.m

import numpy as np
import matplotlib.pyplot as plt


t1 = time.time()
# Define MNSV Parameters
N = 2                     # Number of variables
NS = 10                    # Number of samples
MAXIT = 40                # Maximum Number of iterations
OBJ_F = ObjF_S1           # Name of objective function
R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
Best = []
xb = []

# Initialization
NP = NS * (NS + 3) // 2
# R1 = np.tile(R[0, :], (NP, 1))
# R2 = np.tile(R[1, :], (NP, 1))
x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
f = OBJ_F(x)                   #evaluation
for it in range(MAXIT):
  ind = np.argsort(f)
  x = x[ind[:NS]]                                         # choosing the best points


  # eval = OBJ_F(x)
  # print(eval.T)
  a = np.power(0.3, (it/MAXIT))

  z = a*np.cov(x.T) * np.eye(N)
  # z = a*np.cov(x.T)* np.eye(2)
  for i, j in zip(range(NS), np.linspace(0.5, 1, NS)):
    x = np.append(x, np.random.multivariate_normal(x[i], j*z, (NS-i)), axis=0)  # appending new points
  x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
  f = OBJ_F(x)                     #evaluation
  xb.append(x[np.argmin(f)])  #save the best
  Best.append(np.min(f))
  #plot
t2 = time.time()
print(t2-t1)

0.05902576446533203


In [158]:
xb

[array([-5.1093329 , -4.98660711]),
 array([-5.1093329 , -4.98660711]),
 array([-5.1093329 , -4.98660711]),
 array([-3.9698265 , -4.94808744]),
 array([-5.00749791, -4.97851604]),
 array([-5.00749791, -4.97851604]),
 array([-5.00749791, -4.97851604]),
 array([-5.00749791, -4.97851604]),
 array([-5.00749791, -4.97851604]),
 array([-5.00707016, -4.99932733]),
 array([-4.99991403, -4.99720317]),
 array([-5.00137579, -4.99931117]),
 array([-5.00015184, -4.99948008]),
 array([-4.99997707, -4.9999641 ]),
 array([-4.99997707, -4.9999641 ]),
 array([-5.00000273, -5.00000791]),
 array([-4.99999755, -4.99999554]),
 array([-4.99999752, -5.00000026]),
 array([-5.00000028, -5.00000016]),
 array([-4.99999974, -5.00000001]),
 array([-5.00000002, -4.99999986]),
 array([-5.00000004, -4.99999996]),
 array([-5.        , -4.99999997]),
 array([-5.        , -5.00000001]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.

In [138]:
eval

array([4.35614226e-07, 4.35620727e-07, 4.35623910e-07, 4.35629339e-07,
       4.35631243e-07, 4.35639322e-07, 4.35648211e-07, 4.35657633e-07,
       4.35662784e-07, 4.35665129e-07])

### using functionvalue

In [126]:
# MNSV_S1_1.m

import numpy as np
import matplotlib.pyplot as plt


t1 = time.time()
# Define MNSV Parameters
N = 2                     # Number of variables
NS = 10                    # Number of samples
MAXIT = 40                # Maximum Number of iterations
OBJ_F = ObjF_S1           # Name of objective function
R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
Best = []
xb = []

# Initialization
NP = NS * (NS + 3) // 2
# R1 = np.tile(R[0, :], (NP, 1))
# R2 = np.tile(R[1, :], (NP, 1))
x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
f = OBJ_F(x)                   #evaluation
for it in range(MAXIT):
  ind = np.argsort(f)
  x = x[ind[:NS]]                                         # choosing the best points


  eval = OBJ_F(x)
  # print(eval.T)
  a = np.power(0.3, (it/MAXIT))

  z = a*np.cov(x.T) * np.eye(2)
  # z = a*np.cov(x.T)* np.eye(2)
  covcoes =  eval/np.max(eval)                                                # Covariance Coefficients
  for i, j in zip(range(NS), covcoes):
    x = np.append(x, np.random.multivariate_normal(x[i], j*z, (NS-i)), axis=0)  # appending new points
  x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
  f = OBJ_F(x)                     #evaluation
  xb.append(x[np.argmin(f)])  #save the best
  Best.append(np.min(f))
  #plot
t2 = time.time()
print(t2-t1)

0.11528968811035156


In [127]:
xb

[array([-5.97705263, -5.14518589]),
 array([-7.04405697, -4.99117532]),
 array([-4.06268165, -5.90923239]),
 array([-4.06268165, -5.90923239]),
 array([-5.03529378, -4.95396054]),
 array([-5.03529378, -4.95396054]),
 array([-5.03529378, -4.95396054]),
 array([-5.01904072, -5.03443866]),
 array([-4.98985218, -5.00071457]),
 array([-5.00431558, -4.99675845]),
 array([-4.99896317, -5.0003359 ]),
 array([-4.99982802, -4.99991214]),
 array([-4.99988719, -4.99993682]),
 array([-4.99991047, -4.99994231]),
 array([-4.99991826, -4.99995117]),
 array([-4.99993088, -4.99998381]),
 array([-4.99993743, -4.99997064]),
 array([-4.99993884, -4.99997757]),
 array([-4.99994304, -4.99998907]),
 array([-4.99994657, -4.99998528]),
 array([-4.99994819, -4.99998611]),
 array([-4.9999489 , -4.99999661]),
 array([-4.99995065, -4.99999141]),
 array([-4.99995157, -4.99999477]),
 array([-4.99995174, -4.99999775]),
 array([-4.99995253, -4.99999585]),
 array([-4.99995269, -4.99999654]),
 array([-4.99995291, -4.9999

# Comparison

## Seperated

In [190]:
# new

newtimeList = []
newbestList = []
for i in range(40):
  t1 = time.time()
  # Define MNSV Parameters
  N = 2                     # Number of variables
  NS = 10                    # Number of samples
  MAXIT = 40                # Maximum Number of iterations
  OBJ_F = ObjF_S1           # Name of objective function
  R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
  Best = []
  xb = []

  # Initialization
  NP = NS * (NS + 3) // 2
  # R1 = np.tile(R[0, :], (NP, 1))
  # R2 = np.tile(R[1, :], (NP, 1))
  x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
  f = OBJ_F(x)                   #evaluation
  for it in range(MAXIT):
    ind = np.argsort(f)
    x = x[ind[:NS]]                                         # choosing the best points


    # eval = OBJ_F(x)
    # print(eval.T)
    a = np.power(0.3, (it/MAXIT))

    z = a*np.cov(x.T) * np.eye(N)
    # z = a*np.cov(x.T)* np.eye(2)
    for i, j in zip(range(NS), np.linspace(0.5, 1, NS)):
      x = np.append(x, np.random.multivariate_normal(x[i], j*z, (NS-i)), axis=0)  # appending new points
    x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
    f = OBJ_F(x)                     #evaluation
    xb.append(x[np.argmin(f)])  #save the best
    Best.append(np.min(f))
    #plot
  t2 = time.time()
  newtimeList.append(t2-t1)
  newbestList.append(x[np.argmin(f)])


print(np.array(newtimeList).T)
print(np.array(newbestList).T)

[0.17265439 0.08303499 0.1072433  0.12919569 0.15217018 0.21729302
 0.2160151  0.06985307 0.07414174 0.06924081 0.06769848 0.07199335
 0.0840528  0.07859516 0.08207941 0.07519984 0.07644343 0.0798974
 0.07761264 0.08920288 0.08036566 0.08422112 0.08532858 0.09270835
 0.05881095 0.05089188 0.04489708 0.04550052 0.04744482 0.0439713
 0.04434657 0.05121446 0.05122137 0.0448916  0.04819679 0.04889226
 0.05874014 0.04442763 0.04893255 0.0446701 ]
[[-5.         -5.         -5.         -5.         -5.         -5.
  -5.         -5.         -5.         -5.99495864 -5.         -5.
  -5.         -5.         -5.         -4.00504136 -5.         -5.
  -4.99999977 -5.         -5.         -5.         -4.00504136 -5.
  -5.         -5.         -5.         -5.         -5.         -5.
  -5.         -5.         -5.00026818 -5.         -5.         -5.
  -5.         -5.         -5.         -5.00000009]
 [-5.         -5.         -5.         -5.         -5.         -5.
  -5.         -5.         -5.         -5.

In [171]:
newbestList

[array([-5., -5.]),
 array([-5., -5.]),
 array([-4.99371312, -4.9890556 ]),
 array([-5., -5.]),
 array([-5.        , -4.00504136]),
 array([-5., -5.]),
 array([-5.0005729 , -4.99377011]),
 array([-5.        , -5.99495864]),
 array([-5.        , -5.99495864]),
 array([-4.99645928, -4.00685361])]

In [191]:
# old
oldtimeList = []
oldbestList = []
for i in range(40):
  t1 = time.time()
  # Define MNSV Parameters
  N = 2                     # Number of variables
  NS = 10                    # Number of samples
  MAXIT = 40                # Maximum Number of iterations
  OBJ_F = ObjF_S1           # Name of objective function
  R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
  Best = []
  xb = []

  # Initialization
  NP = NS * (NS + 3) // 2
  # R1 = np.tile(R[0, :], (NP, 1))
  # R2 = np.tile(R[1, :], (NP, 1))
  x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
  f = OBJ_F(x)                   #evaluation
  for it in range(MAXIT):
    ind = np.argsort(f)
    x = x[ind[:NS]]                                         # choosing the best points


    # eval = OBJ_F(x)
    # print(eval.T)
    a = np.power(0.3, (it/MAXIT))

    z = a*np.cov(x.T) * np.eye(N)
    # z = a*np.cov(x.T)* np.eye(2)
    for i in range(NS):
      x = np.append(x, np.random.multivariate_normal(x[i], z, (NS-i)), axis=0)  # appending new points
    x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
    f = OBJ_F(x)                     #evaluation
    xb.append(x[np.argmin(f)])  #save the best
    Best.append(np.min(f))
    #plot
  t2 = time.time()
  oldtimeList.append(t2-t1)
  oldbestList.append(x[np.argmin(f)])


print(np.array(oldtimeList).T)
print(np.array(oldbestList).T)

[0.09214258 0.08664227 0.15734291 0.21225953 0.17691183 0.215662
 0.20729423 0.209795   0.13481855 0.18655896 0.18032765 0.10648084
 0.07723999 0.08799291 0.07605457 0.07283425 0.07602954 0.06754208
 0.07517886 0.07612324 0.07431293 0.07443762 0.07989025 0.06257749
 0.05497217 0.04081726 0.0428133  0.04418945 0.04476619 0.04477453
 0.05678606 0.04102921 0.04131222 0.04388905 0.04159713 0.03926516
 0.03968692 0.04014039 0.04482102 0.04468608]
[[-5.         -5.         -5.         -5.         -5.         -5.01056006
  -5.         -5.00003219 -5.         -5.01601974 -5.         -5.
  -5.         -5.         -5.         -5.         -5.         -5.
  -5.         -4.99999988 -5.         -5.         -4.00504137 -5.
  -4.99999952 -5.         -4.99999934 -5.         -5.         -5.
  -5.99495864 -5.         -5.         -5.         -5.         -5.
  -5.00000163 -5.         -5.         -5.        ]
 [-5.         -5.         -5.00000001 -5.         -5.         -5.99604729
  -5.         -4.99998601

In [192]:
oldbestList

[array([-5., -5.]),
 array([-5., -5.]),
 array([-5.        , -5.00000001]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5.01056006, -5.99604729]),
 array([-5., -5.]),
 array([-5.00003219, -4.99998601]),
 array([-5., -5.]),
 array([-5.01601974, -5.00319611]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-4.99999988, -4.99999999]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-4.00504137, -5.        ]),
 array([-5.        , -5.00000001]),
 array([-4.99999952, -5.00000118]),
 array([-5., -5.]),
 array([-4.99999934, -4.99999968]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5.99495864, -5.        ]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5.00000163, -5.0000031 ]),
 array([-5.        , -5.99495864]),
 array([-5., -5.]),
 array([-5., -5.])]

In [193]:
newbestList

[array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5.99495864, -5.        ]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-4.00504136, -5.        ]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-4.99999977, -4.99980779]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-4.00504136, -5.        ]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5.00026818, -4.99788422]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5.        , -5.99495864]),
 array([-5., -5.]),
 array([-5., -5.]),
 array([-5.00000009, -4.99999989])]

In [194]:
np.mean(oldtimeList)

0.08929990530014038

In [195]:
np.mean(newtimeList)

0.0798322856426239

## Together

In [200]:
NuIt = int(input("enter the number of iterations"))


# new

newtimeList = []
newbestList = []
for i in range(NuIt):
  t1 = time.time()
  # Define MNSV Parameters
  N = 2                     # Number of variables
  NS = 10                    # Number of samples
  MAXIT = 40                # Maximum Number of iterations
  OBJ_F = ObjF_S1           # Name of objective function
  R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
  Best = []
  xb = []

  # Initialization
  NP = NS * (NS + 3) // 2
  # R1 = np.tile(R[0, :], (NP, 1))
  # R2 = np.tile(R[1, :], (NP, 1))
  x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
  f = OBJ_F(x)                   #evaluation
  for it in range(MAXIT):
    ind = np.argsort(f)
    x = x[ind[:NS]]                                         # choosing the best points


    # eval = OBJ_F(x)
    # print(eval.T)
    a = np.power(0.3, (it/MAXIT))

    z = a*np.cov(x.T) * np.eye(N)
    # z = a*np.cov(x.T)* np.eye(2)
    for i, j in zip(range(NS), np.linspace(0.5, 1, NS)):
      x = np.append(x, np.random.multivariate_normal(x[i], j*z, (NS-i)), axis=0)  # appending new points
    x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
    f = OBJ_F(x)                     #evaluation
    xb.append(x[np.argmin(f)])  #save the best
    Best.append(np.min(f))
    #plot
  t2 = time.time()
  newtimeList.append(t2-t1)
  newbestList.append(x[np.argmin(f)])


print(np.array(newtimeList).T)
print(np.array(newbestList).T)


# old
oldtimeList = []
oldbestList = []
for i in range(NuIt):
  t1 = time.time()
  # Define MNSV Parameters
  N = 2                     # Number of variables
  NS = 10                    # Number of samples
  MAXIT = 40                # Maximum Number of iterations
  OBJ_F = ObjF_S1           # Name of objective function
  R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
  Best = []
  xb = []

  # Initialization
  NP = NS * (NS + 3) // 2
  # R1 = np.tile(R[0, :], (NP, 1))
  # R2 = np.tile(R[1, :], (NP, 1))
  x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
  f = OBJ_F(x)                   #evaluation
  for it in range(MAXIT):
    ind = np.argsort(f)
    x = x[ind[:NS]]                                         # choosing the best points


    # eval = OBJ_F(x)
    # print(eval.T)
    a = np.power(0.3, (it/MAXIT))

    z = a*np.cov(x.T) * np.eye(N)
    # z = a*np.cov(x.T)* np.eye(2)
    for i in range(NS):
      x = np.append(x, np.random.multivariate_normal(x[i], z, (NS-i)), axis=0)  # appending new points
    x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
    f = OBJ_F(x)                     #evaluation
    xb.append(x[np.argmin(f)])  #save the best
    Best.append(np.min(f))
    #plot
  t2 = time.time()
  oldtimeList.append(t2-t1)
  oldbestList.append(x[np.argmin(f)])


print(np.array(oldtimeList).T)
print(np.array(oldbestList).T)
print("******************************************")
print("new time")
print(np.mean(newtimeList))
print("old time")
print(np.mean(oldtimeList))



enter the number of iterations100
[0.06099224 0.04802656 0.04880214 0.04527116 0.04934525 0.04641175
 0.04887366 0.04980969 0.04456758 0.06978846 0.04829741 0.05989766
 0.04679775 0.04761672 0.04869342 0.0468905  0.05393648 0.0804882
 0.09773922 0.08250523 0.08172178 0.08264232 0.08346486 0.07157731
 0.0721457  0.07262039 0.06630778 0.06868958 0.07278442 0.07114506
 0.07188845 0.06815624 0.0715549  0.06756902 0.07427692 0.08414364
 0.08080864 0.07548809 0.07440305 0.08386469 0.08098936 0.07552814
 0.08004284 0.07954621 0.08243561 0.08794546 0.0813365  0.05115128
 0.04862428 0.04657269 0.04679942 0.05977654 0.05503011 0.05666423
 0.05156803 0.06934905 0.05268025 0.05273843 0.04733729 0.04795861
 0.05084801 0.06754041 0.06086969 0.05264878 0.051615   0.05162764
 0.05451775 0.05274892 0.0513134  0.05030298 0.05347848 0.04671264
 0.04598618 0.04631019 0.0564425  0.04983187 0.0459125  0.04713655
 0.04658103 0.05079341 0.0499897  0.0494175  0.04833245 0.04535699
 0.0454433  0.04477549 0.0441