<a href="https://colab.research.google.com/github/garfield-gray/Soft-Computing/blob/main/ReportOfMNSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In the Name Of God

In [1]:
# importing the requirements
import numpy as np
import time
import scipy as sp
import matplotlib.pyplot as plt

# The raw Form

## Mathematical Benchmarks

### Functions

In [9]:
# RastRigin
# min in (-5, -5)
ObjF_S1 = lambda x: np.power(x[:,0]+5,2) + np.power(x[:,1]+5,2) -10*np.cos(2*np.pi*x[:,0]) -10*np.cos(2*np.pi*x[:,1]) + 20
# Bukin Function
# min in (-10, 1)
ObjF_S2 = lambda x: 100*np.power(np.abs(x[:,1]-0.01*np.power(x[:,0], 2)),0.5)+0.01*np.abs(x[:,0]+10)
# Rosenbrock
# min in (1, 1)
ObjF_S3 = lambda x: 100*np.power(x[:,1]-np.power(x[:,0], 2), 2) + np.power((1-x[:,0]), 2)
# Beale
# min in (3, 0,5)
ObjF_S4 = lambda x: np.power(1.5-x[:,0]+x[:,0]*x[:,1], 2) + np.power(2.25-x[:,0]+x[:,0]*np.power(x[:,1], 2), 2) + np.power(2.625-x[:,0]+x[:,0]*np.power(x[:,1], 3), 2)


### the implementation

In [16]:
# MNSV_S1_1.m

import numpy as np
import matplotlib.pyplot as plt


t1 = time.time()
# Define MNSV Parameters
N = 2                     # Number of variables
NS = 10                    # Number of samples
MAXIT = 40                # Maximum Number of iterations
OBJ_F = ObjF_S2           # Name of objective function
R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
Best = []
xb = []

# Initialization
NP = NS * (NS + 3) // 2
# R1 = np.tile(R[0, :], (NP, 1))
# R2 = np.tile(R[1, :], (NP, 1))
x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
f = OBJ_F(x)                   #evaluation
for it in range(MAXIT):
  ind = np.argsort(f)
  x = x[ind[:NS]]                                         # choosing the best points
  a = np.power(0.3, (it/MAXIT))
  z = a*np.cov(x.T)
  for i in range(NS):
    x = np.append(x, np.random.multivariate_normal(x[i], z, (NS-i)), axis=0)  # appending new points
  x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
  f = OBJ_F(x)                     #evaluation
  xb.append(x[np.argmin(f)])  #save the best
  Best.append(np.min(f))
  #plot
t2 = time.time()
print(t2-t1)

0.05082964897155762


In [17]:
xb

[array([1.21833392, 0.00802327]),
 array([-1.09656228,  0.01101782]),
 array([-1.09656228,  0.01101782]),
 array([-1.09656228,  0.01101782]),
 array([-0.60696726,  0.00417371]),
 array([-0.60696726,  0.00417371]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.00983948]),
 array([-0.99211324,  0.009839

# Modifications

## Covariance based on function

In [21]:
# MNSV_S1_1.m

import numpy as np
import matplotlib.pyplot as plt


t1 = time.time()
# Define MNSV Parameters
N = 2                     # Number of variables
NS = 10                    # Number of samples
MAXIT = 40                # Maximum Number of iterations
OBJ_F = ObjF_S1           # Name of objective function
R = np.array([[-10, 10], [-10, 10]])  # Bounds on decision variables
Best = []
xb = []

# Initialization
NP = NS * (NS + 3) // 2
# R1 = np.tile(R[0, :], (NP, 1))
# R2 = np.tile(R[1, :], (NP, 1))
x = np.random.uniform(R[0, 0], R[0, 1], (NP, 2))
f = OBJ_F(x)                   #evaluation
for it in range(MAXIT):
  ind = np.argsort(f)
  x = x[ind[:NS]]                                         # choosing the best points
  a = np.power(0.3, (it/MAXIT))
  z = a*np.cov(x.T)
  for i in range(NS):
    x = np.append(x, np.random.multivariate_normal(x[i], z, (NS-i)), axis=0)  # appending new points
  x = np.minimum(np.maximum(x, R[:,0]), R[:,1])     # making sure we're in right bounderies
  f = OBJ_F(x)                     #evaluation
  xb.append(x[np.argmin(f)])  #save the best
  Best.append(np.min(f))
  #plot
t2 = time.time()
print(t2-t1)

0.04343152046203613


In [22]:
xb

[array([-5.13532229, -5.00202435]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99284703, -4.98523821]),
 array([-4.99659787, -4.98796022]),
 array([-4.99855898, -5.0034141 ]),
 array([-5.00064652, -4.99892548]),
 array([-5.00064652, -4.99892548]),
 array([-5.00006542, -4.9995854 ]),
 array([-5.00005358, -4.99993323]),
 array([-4.99997262, -4.99994028]),
 array([-4.99999474, -4.99998426]),
 array([-4.99999851, -4.99999026]),
 array([-5.00000083, -4.99999533]),
 array([-5.00000052, -4.99999748]),
 array([-5.00000009, -4.9999992 ]),
 array([-5.00000001, -4.99999972]),
 array([-4.99999991, -4.99999991]),
 array([-5.00000003, -4.99999991]),
 array([-5.00000003, -4.9999